package base.entities;
// Generated Jan 17, 2018 6:03:15 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Account", catalog = "HighTechStore")
public class Account implements java.io.Serializable {

	private String userName;
	private String password;
	private String name;
	private String address;
	private String phoneNumber;
	private Date joinTime;
	private String photo;
	private String email;
	private boolean enabled;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);
	private Set<Imports> importses = new HashSet<Imports>(0);

	public Account() {
	}

	public Account(String userName, String password, String name, String address, String phoneNumber, Date joinTime,
			String email, boolean enabled) {
		this.userName = userName;
		this.password = password;
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.joinTime = joinTime;
		this.email = email;
		this.enabled = enabled;
	}

	public Account(String userName, String password, String name, String address, String phoneNumber, Date joinTime,
			String photo, String email, boolean enabled, Set<UserRole> userRoles, Set<Imports> importses) {
		this.userName = userName;
		this.password = password;
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.joinTime = joinTime;
		this.photo = photo;
		this.email = email;
		this.enabled = enabled;
		this.userRoles = userRoles;
		this.importses = importses;
	}

	@Id

	@Column(name = "UserName", unique = true, nullable = false, length = 250)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", nullable = false, length = 1073741823)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PhoneNumber", nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JoinTime", nullable = false, length = 23)
	public Date getJoinTime() {
		return this.joinTime;
	}

	public void setJoinTime(Date joinTime) {
		this.joinTime = joinTime;
	}

	@Column(name = "Photo")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "Email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Imports> getImportses() {
		return this.importses;
	}

	public void setImportses(Set<Imports> importses) {
		this.importses = importses;
	}

}
