package base.entities;
// Generated Jan 10, 2018 3:32:46 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Imports generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Imports", catalog = "HighTechStore")
public class Imports implements java.io.Serializable {

	private int id;
	private Account account;
	private Date timeCreation;
	private Set<ImportDetail> importDetails = new HashSet<ImportDetail>(0);

	public Imports() {
	}

	public Imports(int id, Account account, Date timeCreation) {
		this.id = id;
		this.account = account;
		this.timeCreation = timeCreation;
	}

	public Imports(int id, Account account, Date timeCreation, Set<ImportDetail> importDetails) {
		this.id = id;
		this.account = account;
		this.timeCreation = timeCreation;
		this.importDetails = importDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Creator", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TimeCreation", nullable = false, length = 23)
	public Date getTimeCreation() {
		return this.timeCreation;
	}

	public void setTimeCreation(Date timeCreation) {
		this.timeCreation = timeCreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imports")
	public Set<ImportDetail> getImportDetails() {
		return this.importDetails;
	}

	public void setImportDetails(Set<ImportDetail> importDetails) {
		this.importDetails = importDetails;
	}

}
