package base.entities;
// Generated Dec 23, 2017 8:53:57 AM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "Supplier", catalog = "HighTechStore")
public class Supplier implements java.io.Serializable {

	private int id;
	private String name;
	private String address;
	private String phoneNumber;
	private boolean status;
	private Set<ImportDetail> importDetails = new HashSet<ImportDetail>(0);

	public Supplier() {
	}

	public Supplier(int id, String name, String address, String phoneNumber, boolean status) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.status = status;
	}

	public Supplier(int id, String name, String address, String phoneNumber, boolean status,
			Set<ImportDetail> importDetails) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.status = status;
		this.importDetails = importDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", nullable = false, length = 1073741823)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PhoneNumber", nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<ImportDetail> getImportDetails() {
		return this.importDetails;
	}

	public void setImportDetails(Set<ImportDetail> importDetails) {
		this.importDetails = importDetails;
	}

}
