package base.entities;
// Generated Jan 11, 2018 9:32:50 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "UserRole", catalog = "HighTechStore")
public class UserRole implements java.io.Serializable {

	private UserRoleId id;
	private Account account;
	private Role role;
	private boolean enabled;

	public UserRole() {
	}

	public UserRole(UserRoleId id, Account account, Role role, boolean enabled) {
		this.id = id;
		this.account = account;
		this.role = role;
		this.enabled = enabled;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "UserName", nullable = false, length = 250)),
			@AttributeOverride(name = "roleId", column = @Column(name = "RoleID", nullable = false)) })
	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserName", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleID", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "Enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
